CREATE TABLE IF NOT EXISTS "task" (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES "user"(id) ON DELETE CASCADE,
    task_type_id UUID REFERENCES "task_type"(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    priority "priority" NOT NULL DEFAULT 'NAN',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    date_start TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    date_end TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    status "taskstatus" NOT NULL DEFAULT 'ACTIV'
);